### ISSUE TITLE
Question: How to use this tool?

### ISSUE THREAD

**Issue by sideshowbarker** [MattIPv4/github-first-contributions#16]
How do I actually use this tool?

I’ve tried doing `node index.js` (after `npm install`), but I get this:

```
$ node index.js
node:internal/modules/cjs/loader:1222
  throw err;
  ^

Error: Cannot find module './token'
Require stack:
- /Users/mike/workspace/github-first-contributions/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/mike/workspace/github-first-contributions/index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/mike/workspace/github-first-contributions/index.js' ]
}

Node.js v22.4.0
```

**Comment by MattIPv4** [comment]
I think you'll want a `token.js` file locally that just exports a string with your GitHub token.

Also worth noting that this project uses Node.js 16 per [.nvmrc](https://github.com/MattIPv4/github-first-contributions/blob/master/.nvmrc).

**Comment by sideshowbarker** [comment]
> I think you'll want a `token.js` file locally that just exports a string with your GitHub token.

OK, thanks much — did that

> Also worth noting that this project uses Node.js 16 per [.nvmrc](https://github.com/MattIPv4/github-first-contributions/blob/master/.nvmrc?rgh-link-date=2024-07-13T00%3A41%3A34Z).

OK, I installed `nvm` and configured it, and my environment is now running the `index.js` with node v16.20.0 — but now I get an _“Octokit is not a constructor”_ fatal error:

```
$ node --version
v16.20.0

mike@Darwin ~/workspace/github-first-contributions (master)
$ node index.js
PRs newer than 2024-05-13...

digitalocean/doctl
/Users/mike/workspace/github-first-contributions/src/firstPRs.js:10
        this.octokit = new Octokit({auth: opts.githubToken});
                       ^

TypeError: Octokit is not a constructor
    at new firstPRs (/Users/mike/workspace/github-first-contributions/src/firstPRs.js:10:24)
    at main (/Users/mike/workspace/github-first-contributions/index.js:133:26)
    at Object.<anonymous> (/Users/mike/workspace/github-first-contributions/index.js:152:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by sideshowbarker** [comment]
Nevermind, I fixed by doing this:
```diff
-const Octokit = require('@octokit/rest');
+const { Octokit } = require('@octokit/rest');
```

**Comment by sideshowbarker** [comment]
🎉 Thanks much — it’s working perfectly for me now.

Before I discovered this tool (less than a hour ago) I had otherwise been planning to write something myself to try to get the "their first in @org" or "their first ever" data. But this tool is pretty much exactly what I had been looking for.

So, thanks again.

(All that said, I really which the GitHub API would actually expose this data…)
